export enum Service {
  HOUSEKEEPING = 'HOUSEKEEPING',
  DISPATCH_DELIVERY = 'DISPATCH_DELIVERY',
  FUMIGATION = 'FUMIGATION',
  DEEP_CLEANING = 'DEEP_CLEANING',
  ERRANDS = 'ERRANDS',
  LAUNDRY = 'LAUNDRY'
}
